USE PandemyResearch;
GO
DROP TABLE IF EXISTS dbo.STAGE_COVID19Cases_geoRegion;
GO
CREATE TABLE dbo.STAGE_COVID19Cases_geoRegion
(
    geoRegion               VARCHAR(2000) NULL,
    datum                   VARCHAR(2000) NULL,
    entries                 VARCHAR(2000) NULL,
    sumTotal                VARCHAR(2000) NULL,
    timeframe_7d            VARCHAR(2000) NULL,
    offset_last7d           VARCHAR(2000) NULL,
    sumTotal_last7d         VARCHAR(2000) NULL,
    timeframe_14d           VARCHAR(2000) NULL,
    offset_last14d          VARCHAR(2000) NULL,
    sumTotal_last14d        VARCHAR(2000) NULL,
    timeframe_28d           VARCHAR(2000) NULL,
    offset_last28d          VARCHAR(2000) NULL,
    sumTotal_last28d        VARCHAR(2000) NULL,
    timeframe_phase2        VARCHAR(2000) NULL,
    offset_Phase2           VARCHAR(2000) NULL,
    sumTotal_Phase2         VARCHAR(2000) NULL,
    timeframe_phase2b       VARCHAR(2000) NULL,
    offset_Phase2b          VARCHAR(2000) NULL,
    sumTotal_Phase2b        VARCHAR(2000) NULL,
    timeframe_phase3        VARCHAR(2000) NULL,
    offset_Phase3           VARCHAR(2000) NULL,
    sumTotal_Phase3         VARCHAR(2000) NULL,
    timeframe_vacc_info     VARCHAR(2000) NULL,
    offset_vacc_info        VARCHAR(2000) NULL,
    sumTotal_vacc_info      VARCHAR(2000) NULL,
    timeframe_phase4        VARCHAR(2000) NULL,
    offset_Phase4           VARCHAR(2000) NULL,
    sumTotal_Phase4         VARCHAR(2000) NULL,
    timeframe_phase5        VARCHAR(2000) NULL,
    offset_Phase5           VARCHAR(2000) NULL,
    sumTotal_Phase5         VARCHAR(2000) NULL,
    sum7d                   VARCHAR(2000) NULL,
    sum14d                  VARCHAR(2000) NULL,
    mean7d                  VARCHAR(2000) NULL,
    mean14d                 VARCHAR(2000) NULL,
    timeframe_all VARCHAR(2000) NULL,
    entries_diff_last_age   VARCHAR(2000) NULL,
    pop                     VARCHAR(2000) NULL,
    inz_entries             VARCHAR(2000) NULL,
    inzmean7d               VARCHAR(2000) NULL,
    inzmean14d              VARCHAR(2000) NULL,
    inzsumTotal             VARCHAR(2000) NULL,
    inzsumTotal_last7d      VARCHAR(2000) NULL,
    inzsumTotal_last14d     VARCHAR(2000) NULL,
    inzsumTotal_last28d     VARCHAR(2000) NULL,
    inzsumTotal_Phase2      VARCHAR(2000) NULL,
    inzsumTotal_Phase2b     VARCHAR(2000) NULL,
    inzsumTotal_Phase3      VARCHAR(2000) NULL,
    inzsumTotal_Phase4      VARCHAR(2000) NULL,
    inzsumTotal_Phase5      VARCHAR(2000) NULL,
    inzsum7d                VARCHAR(2000) NULL,
    inzsum14d               VARCHAR(2000) NULL,
    sumdelta7d              VARCHAR(2000) NULL,
    inzdelta7d              VARCHAR(2000) NULL,
    type                    VARCHAR(2000) NULL,
    type_variant            VARCHAR(2000) NULL,
    version                 VARCHAR(2000) NULL,
    datum_unit              VARCHAR(2000) NULL,
    entries_letzter_stand   VARCHAR(2000) NULL,
    entries_neu_gemeldet    VARCHAR(2000) NULL,
    entries_diff_last       VARCHAR(2000) NULL
);
GO

DROP TABLE IF EXISTS dbo.STAGE_COVID19Death_geoRegion;
GO
CREATE TABLE dbo.STAGE_COVID19Death_geoRegion
(
    geoRegion              VARCHAR(2000) NULL,
    datum                  VARCHAR(2000) NULL,
    entries                VARCHAR(2000) NULL,
    sumTotal               VARCHAR(2000) NULL,
    timeframe_7d           VARCHAR(2000) NULL,
    offset_last7d          VARCHAR(2000) NULL,
    sumTotal_last7d        VARCHAR(2000) NULL,
    timeframe_14d          VARCHAR(2000) NULL,
    offset_last14d         VARCHAR(2000) NULL,
    sumTotal_last14d       VARCHAR(2000) NULL,
    timeframe_28d          VARCHAR(2000) NULL,
    offset_last28d         VARCHAR(2000) NULL,
    sumTotal_last28d       VARCHAR(2000) NULL,
    timeframe_phase2       VARCHAR(2000) NULL,
    offset_Phase2          VARCHAR(2000) NULL,
    sumTotal_Phase2        VARCHAR(2000) NULL,
    timeframe_phase2b      VARCHAR(2000) NULL,
    offset_Phase2b         VARCHAR(2000) NULL,
    sumTotal_Phase2b       VARCHAR(2000) NULL,
    timeframe_phase3       VARCHAR(2000) NULL,
    offset_Phase3          VARCHAR(2000) NULL,
    sumTotal_Phase3        VARCHAR(2000) NULL,
    timeframe_vacc_info    VARCHAR(2000) NULL,
    offset_vacc_info       VARCHAR(2000) NULL,
    sumTotal_vacc_info     VARCHAR(2000) NULL,
    timeframe_phase4       VARCHAR(2000) NULL,
    offset_Phase4          VARCHAR(2000) NULL,
    sumTotal_Phase4        VARCHAR(2000) NULL,
    timeframe_phase5       VARCHAR(2000) NULL,
    offset_Phase5          VARCHAR(2000) NULL,
    sumTotal_Phase5        VARCHAR(2000) NULL,
    sum7d                  VARCHAR(2000) NULL,
    sum14d                 VARCHAR(2000) NULL,
    mean7d                 VARCHAR(2000) NULL,
    mean14d                VARCHAR(2000) NULL,
    timeframe_all          VARCHAR(2000) NULL,
    entries_diff_last_age  VARCHAR(2000) NULL,
    pop                    VARCHAR(2000) NULL,
    inz_entries            VARCHAR(2000) NULL,
    inzmean7d              VARCHAR(2000) NULL,
    inzmean14d             VARCHAR(2000) NULL,
    inzsumTotal            VARCHAR(2000) NULL,
    inzsumTotal_last7d     VARCHAR(2000) NULL,
    inzsumTotal_last14d    VARCHAR(2000) NULL,
    inzsumTotal_last28d    VARCHAR(2000) NULL,
    inzsumTotal_Phase2     VARCHAR(2000) NULL,
    inzsumTotal_Phase2b    VARCHAR(2000) NULL,
    inzsumTotal_Phase3     VARCHAR(2000) NULL,
    inzsumTotal_Phase4     VARCHAR(2000) NULL,
    inzsumTotal_Phase5     VARCHAR(2000) NULL,
    inzsum7d               VARCHAR(2000) NULL,
    inzsum14d              VARCHAR(2000) NULL,
    sumdelta7d              VARCHAR(2000) NULL,
    inzdelta7d              VARCHAR(2000) NULL,
    type                    VARCHAR(2000) NULL,
    type_variant            VARCHAR(2000) NULL,
    version                 VARCHAR(2000) NULL,
    datum_unit              VARCHAR(2000) NULL,
    entries_letzter_stand   VARCHAR(2000) NULL,
    entries_neu_gemeldet    VARCHAR(2000) NULL,
    entries_diff_last       VARCHAR(2000) NULL
);
GO


-- =========================================================
-- STAGE-Tabelle: COVID19Test_geoRegion_all
-- Die Spalten entsprechen der Reihenfolge der BAG-CSV-Datei.
-- Alle Quelldaten werden zunächst als VARCHAR importiert.
-- Die Datentypkonvertierung erfolgt erst bei der Transformation.
-- =========================================================

DROP TABLE IF EXISTS dbo.STAGE_COVID19Test_geoRegion_all;
GO
CREATE TABLE dbo.STAGE_COVID19Test_geoRegion_all
(
    datum                   VARCHAR(2000) NULL,
    entries                 VARCHAR(2000) NULL,
    entries_pos             VARCHAR(2000) NULL,
    entries_neg             VARCHAR(2000) NULL,
    sumTotal                VARCHAR(2000) NULL,
    timeframe_7d            VARCHAR(2000) NULL,
    sumTotal_last7d         VARCHAR(2000) NULL,
    timeframe_14d           VARCHAR(2000) NULL,
    sumTotal_last14d        VARCHAR(2000) NULL,
    timeframe_28d           VARCHAR(2000) NULL,
    sumTotal_last28d        VARCHAR(2000) NULL,
    timeframe_phase2        VARCHAR(2000) NULL,
    sumTotal_Phase2         VARCHAR(2000) NULL,
    timeframe_phase2b       VARCHAR(2000) NULL,
    sumTotal_Phase2b        VARCHAR(2000) NULL,
    timeframe_phase3        VARCHAR(2000) NULL,
    sumTotal_Phase3         VARCHAR(2000) NULL,
    timeframe_phase4        VARCHAR(2000) NULL,
    sumTotal_Phase4         VARCHAR(2000) NULL,
    timeframe_phase5        VARCHAR(2000) NULL,
    sumTotal_Phase5         VARCHAR(2000) NULL,
    sum7d                   VARCHAR(2000) NULL,
    sum14d                  VARCHAR(2000) NULL,
    mean7d                  VARCHAR(2000) NULL,
    mean14d                 VARCHAR(2000) NULL,
    pos_anteil              VARCHAR(2000) NULL,
    pos_anteil_mean7d       VARCHAR(2000) NULL,
    timeframe_all           VARCHAR(2000) NULL,
    anteil_pos_all          VARCHAR(2000) NULL,
    anteil_pos_14           VARCHAR(2000) NULL,
    anteil_pos_28           VARCHAR(2000) NULL,
    anteil_pos_phase2       VARCHAR(2000) NULL,
    anteil_pos_phase2b      VARCHAR(2000) NULL,
    anteil_pos_phase3       VARCHAR(2000) NULL,
    anteil_pos_phase4       VARCHAR(2000) NULL,
    anteil_pos_phase5       VARCHAR(2000) NULL,
    pop                     VARCHAR(2000) NULL,
    inz_entries             VARCHAR(2000) NULL,
    inzmean7d               VARCHAR(2000) NULL,
    inzmean14d              VARCHAR(2000) NULL,
    inzsumTotal             VARCHAR(2000) NULL,
    inzsumTotal_last7d      VARCHAR(2000) NULL,
    inzsumTotal_last14d     VARCHAR(2000) NULL,
    inzsumTotal_last28d     VARCHAR(2000) NULL,
    inzsumTotal_Phase2      VARCHAR(2000) NULL,
    inzsumTotal_Phase2b     VARCHAR(2000) NULL,
    inzsumTotal_Phase3      VARCHAR(2000) NULL,
    inzsumTotal_Phase4      VARCHAR(2000) NULL,
    inzsumTotal_Phase5      VARCHAR(2000) NULL,
    inzsum7d                VARCHAR(2000) NULL,
    inzsum14d               VARCHAR(2000) NULL,
    type                    VARCHAR(2000) NULL,
    version                 VARCHAR(2000) NULL,
    datum_unit              VARCHAR(2000) NULL,
    nachweismethode         VARCHAR(2000) NULL,
    geoRegion               VARCHAR(2000) NULL,
    entries_diff_last_age   VARCHAR(2000) NULL,
    entries_diff_last       VARCHAR(2000) NULL
);
GO

-- ============================================================
-- STAGE-Tabelle: COVID19HospCapacity_geoRegion
-- Die Spalten entsprechen der Reihenfolge der BAG-CSV-Datei.
-- Alle Quelldaten werden zunächst als VARCHAR importiert.
-- Die Datentypkonvertierung erfolgt erst bei der Transformation.
-- ============================================================

DROP TABLE IF EXISTS dbo.STAGE_COVID19HospCapacity_geoRegion;
GO
CREATE TABLE dbo.STAGE_COVID19HospCapacity_geoRegion
(
    date                                VARCHAR(2000) NULL,
    geoRegion                           VARCHAR(2000) NULL,
    ICU_AllPatients                     VARCHAR(2000) NULL,
    ICU_Covid19Patients                 VARCHAR(2000) NULL,
    ICU_Capacity                        VARCHAR(2000) NULL,
    Total_AllPatients                   VARCHAR(2000) NULL,
    Total_Covid19Patients               VARCHAR(2000) NULL,
    Total_Capacity                      VARCHAR(2000) NULL,
    ICU_NonCovid19Patients              VARCHAR(2000) NULL,
    ICU_FreeCapacity                    VARCHAR(2000) NULL,
    Total_NonCovid19Patients            VARCHAR(2000) NULL,
    Total_FreeCapacity                  VARCHAR(2000) NULL,
    timeframe_14d                       VARCHAR(2000) NULL,
    timeframe_28d                       VARCHAR(2000) NULL,
    timeframe_phase2                    VARCHAR(2000) NULL,
    timeframe_phase2b                   VARCHAR(2000) NULL,
    timeframe_phase3                    VARCHAR(2000) NULL,
    timeframe_phase4                    VARCHAR(2000) NULL,
    timeframe_phase5                    VARCHAR(2000) NULL,
    timeframe_all                       VARCHAR(2000) NULL,
    Total_Capacity_mean15d              VARCHAR(2000) NULL,
    Total_AllPatients_mean15d           VARCHAR(2000) NULL,
    Total_Covid19Patients_mean15d       VARCHAR(2000) NULL,
    Total_NonCovid19Patients_mean15d    VARCHAR(2000) NULL,
    Total_FreeCapacity_mean15d          VARCHAR(2000) NULL,
    ICU_Capacity_mean15d                VARCHAR(2000) NULL,
    ICU_AllPatients_mean15d             VARCHAR(2000) NULL,
    ICU_Covid19Patients_mean15d         VARCHAR(2000) NULL,
    ICU_NonCovid19Patients_mean15d      VARCHAR(2000) NULL,
    ICU_FreeCapacity_mean15d            VARCHAR(2000) NULL,
    type_variant                        VARCHAR(2000) NULL,
    ICUPercent_AllPatients              VARCHAR(2000) NULL,
    ICUPercent_NonCovid19Patients       VARCHAR(2000) NULL,
    ICUPercent_Covid19Patients          VARCHAR(2000) NULL,
    ICUPercent_FreeCapacity             VARCHAR(2000) NULL,
    ICUPercent_Capacity                 VARCHAR(2000) NULL,
    TotalPercent_AllPatients            VARCHAR(2000) NULL,
    TotalPercent_NonCovid19Patients     VARCHAR(2000) NULL,
    TotalPercent_Covid19Patients        VARCHAR(2000) NULL,
    TotalPercent_FreeCapacity           VARCHAR(2000) NULL,
    TotalPercent_Capacity               VARCHAR(2000) NULL,
    ICU_exists                          VARCHAR(2000) NULL,
    Total_exists                        VARCHAR(2000) NULL,
    type                                VARCHAR(2000) NULL,
    version                             VARCHAR(2000) NULL
);
GO